server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123root123
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# example values
#
indexing-settings:
  configSites:
    #    - url: https://www.lenta.ru
    #      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.module.ru
      name: Module
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.error.test
      name: test.error
